### DISCUSSION TITLE
List css control

### DISCUSSION THREAD

**Discussion by lozdown** [sqlpage/SQLPage#201] [Q&A]
I am trying to control the presentation of lists. I have a minimal set of files  which work but does not respond to the configured  css styles. What am I doing wrong?

### index.sql

```css
select 
	'shell'	as component,
    'SQLPage testbench'	as title,
    '/'	as link,
    'details.css'	as css;
    
select 
	'list' as component,
	'ldb-class'	as class,
	'Tests' as title;
select 
	'Test item' as title, 'ldb1' as id;
```

### details.css

```css
.ldb-class {
	background-color: Lavender;
}

#ldb1 (
	background-color: Red;
}

```
