### DISCUSSION TITLE
Adding the "wide-table" option

### DISCUSSION THREAD

**Discussion by pchemguy** [sqlpage/SQLPage#421] [Q&A] [answered]
Regarding this [wide-table](https://github.com/lovasoa/SQLpage/discussions/397), would it be ok to integrate this option in SQLPage?

I guess there are a few approaches to implement it. Perhaps, adding

```css
.fit_wide_table {
  width: fit-content;
}
```
or
```css
.wide_table {
  width: fit-content;
}
```
to the integrated SQLPage CSS (that woul be sqlpage/sqlpage.css, right?).

Another option would be adding "fit_wide_table" (or "wide_table") boolean to the table component and adjusting the template file.

What do you think?
