### DISCUSSION TITLE
Control of column widths on tables

### DISCUSSION THREAD

**Discussion by lozdown** [sqlpage/SQLPage#558] [Q&A] [answered]
I would like to control the table component column widths. How best can this be done?

**Comment by lovasoa** [comment, marked as answer]
Hello !

You can use css for that:

```sql
select 'shell' as component, 'custom_table_width.css' as css;

select 'table' as component, 'my_table' as id;
select * from my_table;
```

and in `custom_table_width.css`:

```css
#my_table th:nth-child(1),
#my_table td:nth-child(1) {
    width: 90%; /* adjust percentage as needed */
}

#my_table th:nth-child(2),
#my_table td:nth-child(2) {
    width: 10%;
}
```

**Reply by lovasoa** [reply]
If your table has simple single-word column names like "Product" and "Price", you can simplify this to:

```css
#my_table .Product {
    width: 90%; /* adjust percentage as needed */
}

#my_table .Price {
    width: 10%;
}
```
