### DISCUSSION TITLE
add a top level parameters for the table component to freeze pans

### DISCUSSION THREAD

**Discussion by alexisrc1** [sqlpage/SQLPage#561] [Ideas]
in this example, i can scroll far to the right, so i'd like the first 3 columns to be frozen like it can be done in Excel.
![Sans titre-1](https://github.com/user-attachments/assets/02b2578d-586c-4720-9180-74b899077099)

would be a cool feature :)

**Comment by lovasoa** [comment]
Hey @alexisrc1 !

This would indeed be a nice feature to add to the table component. 
Similarly to this previous question, this is something you can do with a few lines of custom css: https://github.com/lovasoa/SQLpage/discussions/558

```sql
select 'shell' as component, 'custom_table_columns.css' as css;
```

```css
.mycolumn {
  position: sticky;
  left: 0;
  background-color: white !important,
  z-index: 2;
  box-shadow: 0 12px 12px #eee; 
}
```
