### DISCUSSION TITLE
Can JSON be shown in a table?

### DISCUSSION THREAD

**Discussion by ArianYN** [sqlpage/SQLPage#583] [Q&A]
I am trying to SELECT some data from a table. A column of that data is in jsonb, but in SQLPage it just shows up as [object].

Is there any way to get it to actually show the json? Maybe in a way like Grafana where the inital cell is small, but when you click, you can expand it to see the entire thing?

**Comment by lovasoa** [comment]
Hello !
  You can show a jsonb column by converting it to text first. You can also format the json to make it more readable:

```sql
select 'table' as component;

select jsonb_pretty(my_jsonb_column) as "JSON information" from my_table;
```

There is no builtin way to reproduce the grafana effect, but you can reproduce it in css:

```css
td {
  max-width: 200px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

td:hover {
  max-width: none;
  white-space: normal;
  overflow: visible;
}
```
